server:
  port: 8083


spring:
  datasource:
    username: root
    password: 124823
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=UTC

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  redis:
    host: 127.0.0.1
    port: 6379
    password: #密码
    database: 0 #指定数据库，默认为0
    timeout: 0 #连接超时时间，单位毫秒，默认为0
    ssl: false # 是否启用SSL连接，默认false
    pool: #连接池配置
      max-active: 8 #最大活跃连接数，默认8个。
      max-idle: 8 #最大空闲连接数，默认8个。
      max-wait: -1 #获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
      min-idle: 0 #最小空闲连接数，默认0。

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# jwt配置
jwtSecret: 124823
expire: 7
